// <auto-generated />
using GamesRestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesRestApi.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamesRestApi.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Release")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An open-world action-adventure game set in Hyrule.",
                            Image = "https://example.com/zelda.jpg",
                            Publisher = "Nintendo",
                            Release = "March 3, 2017",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An action-adventure game based on Norse mythology.",
                            Image = "https://example.com/godofwar.jpg",
                            Publisher = "Sony Interactive Entertainment",
                            Release = "April 20, 2018",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An epic tale of life in America’s unforgiving heartland.",
                            Image = "https://example.com/rdr2.jpg",
                            Publisher = "Rockstar Games",
                            Release = "October 26, 2018",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An open-world action RPG set in Night City.",
                            Image = "https://example.com/cyberpunk2077.jpg",
                            Publisher = "CD Projekt",
                            Release = "December 10, 2020",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A dark fantasy action RPG developed with George R. R. Martin.",
                            Image = "https://example.com/eldenring.jpg",
                            Publisher = "Bandai Namco",
                            Release = "February 25, 2022",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A sandbox survival game with procedural worlds.",
                            Image = "https://example.com/minecraft.jpg",
                            Publisher = "Mojang Studios",
                            Release = "November 18, 2011",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A story-driven RPG set in a visually stunning fantasy universe.",
                            Image = "https://example.com/witcher3.jpg",
                            Publisher = "CD Projekt",
                            Release = "May 19, 2015",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 8,
                            Description = "An open-world action game set in Los Santos.",
                            Image = "https://example.com/gtav.jpg",
                            Publisher = "Rockstar Games",
                            Release = "September 17, 2013",
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 9,
                            Description = "An action RPG exploring post-apocalyptic lands ruled by machines.",
                            Image = "https://example.com/horizonfw.jpg",
                            Publisher = "Sony Interactive Entertainment",
                            Release = "February 18, 2022",
                            Title = "Horizon Forbidden West"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A Viking-themed open-world action RPG.",
                            Image = "https://example.com/acvalhalla.jpg",
                            Publisher = "Ubisoft",
                            Release = "November 10, 2020",
                            Title = "Assassin’s Creed Valhalla"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
